# Example showcasing the use of multiple variables within the visualizing paths

# When switching to "next" chart, the visualization moves through the different possible values of CLASS
# Additionally, both DATASET and CLASS are possible to change in the GUI through sliders

# <CARD_DIR> is substituted by the base dir where the card is located
filepath = "<CARD_DIR>/../data/complex_study/{{DATASET}}/{{CLASS}}/time_series.json"

chart_style = "line"

# The value pivot_chart references will be the switching factor when going to the "next" chart in the GUI
# For example, next chart of .../dataset_alpha/class_A/... will be .../dataset_alpha/class_B/...
pivot_chart = {{CLASS}}
