# Overlay TIC with a single precursor file per class (named variable, no overlay var).

[global]
pivot_chart = "{{CLASS}}"
chart_style = ["line", "scatter"]

filepath = [
  "<CARD_DIR>/../../__data/R10_Standard_Mixes/iterative_excL_20eV/TIC.json",
  "<CARD_DIR>/../../__data/R10_Standard_Mixes/iterative_excL_20eV/{{CLASS}}/ms1_precursor-{{PRECURSOR}}.json"
]
